In [2]:
import pandas as pd
df = pd.read_excel(r"C:\Users\DELL\OneDrive\Documents\Semester 6 Lab Manual\Machine Learning\Decision tree.xlsx")
df

       company                  job     degree  salery
0       google      sales executive  bachelore       1
1       google   business executive     master       0
2       google  conputer programmer  bachelore       1
3       google      sales executive     master       0
4       google   business executive  bachelore       1
5       google  conputer programmer     master       1
6     facebook      sales executive  bachelore       0
7     facebook   business executive     master       1
8     facebook  conputer programmer  bachelore       1
9     facebook      sales executive     master       0
10  abc pharma   business executive  bachelore       1
11  abc pharma  conputer programmer     master       0
12  abc pharma      sales executive  bachelore       0
13  abc pharma   business executive     master       1
14  abc pharma  conputer programmer  bachelore       1
15  abc pharma      sales executive     master       0

In [6]:
x=df[['company','job','degree']]
x

       company                  job     degree
0       google      sales executive  bachelore
1       google   business executive     master
2       google  conputer programmer  bachelore
3       google      sales executive     master
4       google   business executive  bachelore
5       google  conputer programmer     master
6     facebook      sales executive  bachelore
7     facebook   business executive     master
8     facebook  conputer programmer  bachelore
9     facebook      sales executive     master
10  abc pharma   business executive  bachelore
11  abc pharma  conputer programmer     master
12  abc pharma      sales executive  bachelore
13  abc pharma   business executive     master
14  abc pharma  conputer programmer  bachelore
15  abc pharma      sales executive     master

In [8]:
y=df['salery']
y

0     1
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     0
10    1
11    0
12    0
13    1
14    1
15    0
Name: salery, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder

In [12]:
x['comn'] = LabelEncoder().fit_transform(x['company'])
x['jobn'] = LabelEncoder().fit_transform(x['job'])
x['degreen'] = LabelEncoder().fit_transform(x['degree'])
x = x[['comn','jobn','degreen']]
x

    comn  jobn  degreen
0      2     2        0
1      2     0        1
2      2     1        0
3      2     2        1
4      2     0        0
5      2     1        1
6      1     2        0
7      1     0        1
8      1     1        0
9      1     2        1
10     0     0        0
11     0     1        1
12     0     2        0
13     0     0        1
14     0     1        0
15     0     2        1

In [14]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x,y)

DecisionTreeClassifier()

In [16]:
model.predict([[0,0,1]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)