In [1]:
##Decision Tree
import pandas as pd

In [2]:
df = pd.read_csv(r"salaries.csv")
df.head()

  company                  job     degree  salery
0  google      sales executive  bachelore       1
1  google   business executive     master       0
2  google  conputer programmer  bachelore       1
3  google      sales executive     master       0
4  google   business executive  bachelore       1

In [3]:
inputs = df.drop('salery',axis='columns')
inputs

       company                  job     degree
0       google      sales executive  bachelore
1       google   business executive     master
2       google  conputer programmer  bachelore
3       google      sales executive     master
4       google   business executive  bachelore
5       google  conputer programmer     master
6     facebook      sales executive  bachelore
7     facebook   business executive     master
8     facebook  conputer programmer  bachelore
9     facebook      sales executive     master
10  abc pharma   business executive  bachelore
11  abc pharma  conputer programmer     master
12  abc pharma      sales executive  bachelore
13  abc pharma   business executive     master
14  abc pharma  conputer programmer  bachelore
15  abc pharma      sales executive     master

In [4]:
target = df['salery']
target

0     1
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     0
10    1
11    0
12    0
13    1
14    1
15    0
Name: salery, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

In [7]:
inputs['company_n'] = le_company.fit_transform(inputs['company'])
inputs['job_n'] = le_job.fit_transform(inputs['job'])
inputs['degree_n'] = le_degree.fit_transform(inputs['degree'])
inputs

       company                  job     degree  company_n  job_n  degree_n
0       google      sales executive  bachelore          2      2         0
1       google   business executive     master          2      0         1
2       google  conputer programmer  bachelore          2      1         0
3       google      sales executive     master          2      2         1
4       google   business executive  bachelore          2      0         0
5       google  conputer programmer     master          2      1         1
6     facebook      sales executive  bachelore          1      2         0
7     facebook   business executive     master          1      0         1
8     facebook  conputer programmer  bachelore          1      1         0
9     facebook      sales executive     master          1      2         1
10  abc pharma   business executive  bachelore          0      0         0
11  abc pharma  conputer programmer     master          0      1         1
12  abc pharma      sales executive  bachelore          0      2         0
13  abc pharma   business executive     master          0      0         1
14  abc pharma  conputer programmer  bachelore          0      1         0
15  abc pharma      sales executive     master          0      2         1

In [8]:
inputs_n = inputs.drop(['company','job','degree'],axis='columns')

In [9]:
inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      0         1
2           2      1         0
3           2      2         1
4           2      0         0
5           2      1         1
6           1      2         0
7           1      0         1
8           1      1         0
9           1      2         1
10          0      0         0
11          0      1         1
12          0      2         0
13          0      0         1
14          0      1         0
15          0      2         1

In [10]:
target

0     1
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     0
10    1
11    0
12    0
13    1
14    1
15    0
Name: salery, dtype: int64

In [11]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [12]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [13]:
model.score(inputs_n,target)

1.0

In [15]:
##**Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?**

In [16]:
model.predict([[2,1,0]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [17]:
##**Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?**

In [18]:
model.predict([[2,1,1]])

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)